targets:
  $default:
    builders:
      event_sync_generator|event_sync:
        generate_for:
          - lib/*
        enabled: true

builders:
  event_sync:
    target: ":event_sync_generator"
    import: "package:event_sync_generator/builder.dart"
    builder_factories: ["generateEvents"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]