name: event_sink_generator
description: A new Flutter package project.
version: 0.0.3
homepage:
# TODO: remove this once we deploy this
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  build: ^2.1.1
  source_gen: ^1.2.7
  analyzer: ^5.9.0
  recase: ^4.1.0
  event_sink:
#    path: ../../neutrinographics/event_sink
    git:
      url: git@github.com:neutrinographics/event_sink.git
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  build_test: ^2.1.5