name: event_sync_generator
description: A new Flutter package project.
version: 0.0.1
homepage:
# TODO: remove this once we deploy this
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  build: ^2.3.1
  flutter:
    sdk: flutter
  source_gen: ^1.2.6
  build_config: ^1.1.1
  analyzer: ^4.7.0
  recase: ^4.1.0
  event_sync:
    path: ../event_sync/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  build_test: ^2.1.5
