name: event_sink_generator
description: Used to generate an implementation of an EventSink.
version: 1.0.0
homepage:
# TODO: remove this once we deploy this
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  build: ^2.1.1
  source_gen: ^1.2.6
  recase: ^4.1.0
  analyzer: ^5.0.0
  event_sink:
#    path: ../../neutrinographics/event_sink
    git:
      url: git@github.com:neutrinographics/event_sink.git
      ref: main

dev_dependencies:
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  build_test: ^2.1.5